### ISSUE TITLE
fix delete syntax so it works for mysql as well as postgres

### ISSUE THREAD

**Issue by RobertHeim** [RobertHeim/phpbb-ext-topictags#41]
see https://github.com/RobertHeim/phpbb-ext-topictags/commit/5ece4ea02aa6f739fad741b5632e7ce503cdef3a#commitcomment-9093237

**Comment by RobertHeim** [comment]
waiting for somone to test master branch with postgres. https://github.com/RobertHeim/phpbb-ext-topictags/pull/39

**Comment by EllieFops** [comment]
Sorry about the late reply.  I haven't been able to get a query error on the latest revision in postgres, so that part looks good.

I didn't realize originally that MySQL allowed multi-table DELETE statements as I am more familiar with PgSQL which only allows single table operations with DELETE and allows aliases on tables used in DELETE statements, so I apologize for my pull request (#39) being problematic.

**Comment by RobertHeim** [comment]
Thank you EllieFops!
